services:
  postgres:
    image: postgres:16-alpine
    container_name: fasturl-postgres
    environment:
      POSTGRES_DB: fasturl
      POSTGRES_USER: fasturl
      POSTGRES_PASSWORD: fasturl
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fasturl"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: fasturl-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
